export const APPLICATION_ID = 14075559;
export const ALGORAND_LEDGER = 'TestNet';
export const ESCROW_ADDRESS = 'VKTOVWUYQWKWF5UN6JL2URE3XHBB6NR44JWMQH3RR4ZCCIXRJJ5N7GAZYU';
export const COMPILED_ESCROW = 'AiAHAgOnjdsGBgQAASYCDFNFVFVQX0VTQ1JPVwhXSVRIRFJBVzIEIhJAAAgyBCMSQAArADMAGCQSMwAQJRIQNwAaACgSEDMBECEEEhAzARIhBRIQQAABACEGQ0IAQzMAGCQSMwAQJRIQNwAaACkSEDMBECEEEhAzAhAhBhIQMwEBMgASEDMCATIAEhAzARIhBQ0zAgghBQ0REEAAAQAhBkM=';
export const ASSET_INDEX = 14075549;
export const ASSET_NAME = 'USDTG';

export const ALGOS_DECIMAL_POINTS = 6;
export const ASSET_DECIMAL_POINTS = 2;
export const ALGOS_RATIO = 10 ** ALGOS_DECIMAL_POINTS;
export const ASSET_RATIO = 10 ** ASSET_DECIMAL_POINTS;
export const RATIO_DECIMAL_POINTS = 6;
export const RATIO = 10 ** RATIO_DECIMAL_POINTS;
export const FEE_PERCENTAGE = 3;
